const starter=[{id:1,name:"إبريق أنوكس",price:100,cat:"أباريق",emoji:"🫖"},{id:2,name:"طقم أواني الطبخ",price:249,cat:"أواني الطبخ",emoji:"🍳"},{id:3,name:"كاسرولة أنوكس",price:120,cat:"أواني الطبخ",emoji:"🥘"},{id:4,name:"صينية تقديم",price:80,cat:"أواني منزلية",emoji:"🍽️"}];
let products=JSON.parse(localStorage.getItem("products")||"null")||starter, cart=JSON.parse(localStorage.getItem("cart")||"{}");
const $=s=>document.querySelector(s); function save(){localStorage.setItem("products",JSON.stringify(products));localStorage.setItem("cart",JSON.stringify(cart));render();renderAdmin()}
function render(){let q=$("#search").value.toLowerCase(),c=$("#cat").value;let cats=[...new Set(products.map(p=>p.cat))];$("#cat").innerHTML='<option value="">كل الفئات</option>'+cats.map(x=>`<option ${x===c?"selected":""}>${x}</option>`).join("");$("#products").innerHTML=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.cat===c)).map(p=>`<article class="card"><div class="pic">${p.emoji||"🛍️"}</div><div class="body"><h3>${p.name}</h3><small>${p.cat}</small><div class="price">${p.price} درهم</div><button class="add" onclick="add(${p.id})">أضف للسلة</button></div></article>`).join("")||"<p>لا توجد منتجات.</p>";let n=0,sum=0;$("#items").innerHTML=Object.keys(cart).map(id=>{let p=products.find(x=>x.id==id),q=cart[id];if(!p)return "";n+=q;sum+=p.price*q;return `<div class="row"><span>${p.name}<br>${p.price} × ${q}</span><span><button onclick="chg(${id},-1)">−</button> ${q} <button onclick="chg(${id},1)">+</button></span></div>`}).join("")||"<p>السلة فارغة.</p>";$("#count").textContent=n;$("#total").textContent=sum}
function add(id){cart[id]=(cart[id]||0)+1;save();openCart()}function chg(id,d){cart[id]+=d;if(cart[id]<=0)delete cart[id];save()}function openCart(){$("#cart").classList.add("open")}function closeCart(){$("#cart").classList.remove("open")}function openAdmin(){$("#admin").classList.add("open");renderAdmin()}function closeAdmin(){$("#admin").classList.remove("open")}
function renderAdmin(){$("#adminList").innerHTML=products.map(p=>`<div class="adminrow"><b>${p.name}</b> — ${p.price}dh<br><small>${p.cat}</small><br><button onclick="edit(${p.id})">✏️ تعديل</button><button onclick="del(${p.id})">🗑️ حذف</button></div>`).join("")}
function edit(id){let p=products.find(x=>x.id==id);$("#editId").value=id;$("#pname").value=p.name;$("#pprice").value=p.price;$("#pcat").value=p.cat;$("#pemoji").value=p.emoji||"";openAdmin()}function del(id){if(confirm("حذف هذا المنتج؟")){products=products.filter(p=>p.id!=id);delete cart[id];save()}}
$("#productForm").onsubmit=e=>{e.preventDefault();let id=+$("#editId").value,p={id:id||Date.now(),name:$("#pname").value,price:+$("#pprice").value,cat:$("#pcat").value,emoji:$("#pemoji").value||"🛍️"};if(id)products=products.map(x=>x.id==id?p:x);else products.push(p);e.target.reset();$("#editId").value="";save();alert("تم حفظ المنتج ✅")};
$("#order").onsubmit=e=>{e.preventDefault();if(!Object.keys(cart).length)return alert("السلة فارغة");let f=new FormData(e.target),items=Object.keys(cart).map(id=>{let p=products.find(x=>x.id==id);return `${p.name} x${cart[id]}`}).join("، ");let msg=`السلام عليكم، أريد الطلب:%0A${items}%0Aالاسم: ${f.get("name")}%0Aالهاتف: ${f.get("phone")}%0Aالعنوان: ${f.get("address")}`;location.href="https://wa.me/212718000706?text="+msg};
$("#search").oninput=render;$("#cat").onchange=render;render();renderAdmin();